name: Publish to GitHub Pages

on:
  push:
    branched:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Install Emacs and Make
        run: sudo apt install emacs-nox make --yes

      - name: Build the site
        run: make site

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
